apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER_KEY: root
  POSTGRES_PASSWORD_KEY: myroot1
  POSTGRES_DB_KEY: myapp
  POSTGRES_INIT_KEY: |
    CREATE USER myappuser WITH ENCRYPTED PASSWORD 'myappuserPwd1';
    GRANT ALL PRIVILEGES ON DATABASE myapp to myappuser;
